FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o worker-service ./cmd

FROM alpine:3.19
COPY --from=builder /app/worker-service /worker-service
ENTRYPOINT ["/worker-service"]
