# lbconfig.yaml
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: app-gw-lbconfig
  namespace: default
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTP:80
      defaultActions:
        - type: Redirect
          redirectConfig:
            protocol: HTTPS
            port: "443"
            statusCode: HTTP_301    
    - protocolPort: HTTPS:443
      defaultCertificate: <certificate arn> # put your certificate ARN here